<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\FlashcardQuestions\Object;

use ilCheckboxInputGUI;
use ilFlashcardQuestionsPlugin;
use ilObjFlashcardQuestionsGUI;
use ilPropertyFormGUI;
use ilTextAreaInputGUI;
use ilTextInputGUI;
use srag\DIC\DICTrait;

/**
 * Class ObjSettingsFormGUI
 *
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @package srag\Plugins\FlashcardQuestions\Object
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ObjSettingsFormGUI extends ilPropertyFormGUI {

	use DICTrait;
	const PLUGIN_CLASS_NAME = ilFlashcardQuestionsPlugin::class;
	/**
	 * @var ilObjFlashcardQuestionsGUI
	 */
	protected $parent;


	/**
	 * ObjSettingsFormGUI constructor
	 *
	 * @param ilObjFlashcardQuestionsGUI $parent
	 */
	public function __construct(ilObjFlashcardQuestionsGUI $parent) {
		parent::__construct();

		$this->parent = $parent;

		$this->setForm();
	}


	/**
	 *
	 */
	protected function setForm()/*: void*/ {
		$this->setFormAction(self::dic()->ctrl()->getFormAction($this->parent));

		$this->setTitle(self::plugin()->translate("settings", ilObjFlashcardQuestionsGUI::LANG_MODULE_SETTINGS));

		$this->addCommandButton(ilObjFlashcardQuestionsGUI::CMD_SETTINGS_STORE, self::plugin()
			->translate("save", ilObjFlashcardQuestionsGUI::LANG_MODULE_SETTINGS));

		$title = new ilTextInputGUI(self::plugin()->translate("title", ilObjFlashcardQuestionsGUI::LANG_MODULE_SETTINGS), "title");
		$title->setRequired(true);
		$title->setValue($this->parent->object->getTitle());
		$this->addItem($title);

		$description = new ilTextAreaInputGUI(self::plugin()
			->translate("description", ilObjFlashcardQuestionsGUI::LANG_MODULE_SETTINGS), "description");
		$description->setValue($this->parent->object->getLongDescription());
		$this->addItem($description);

		$online = new ilCheckboxInputGUI(self::plugin()->translate("online", ilObjFlashcardQuestionsGUI::LANG_MODULE_SETTINGS), "online");
		$online->setChecked($this->parent->object->isOnline());
		$this->addItem($online);
	}


	/**
	 *
	 */
	public function updateSettings()/*: void*/ {
		$title = $this->getInput("title");
		$this->parent->object->setTitle($title);

		$description = $this->getInput("description");
		$this->parent->object->setDescription($description);

		$online = boolval($this->getInput("online"));
		$this->parent->object->setOnline($online);

		$this->parent->object->update();
	}
}
