<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */

$id = "xfcq";
$version = "0.2.0";
$ilias_min_version = "5.3.0";
$ilias_max_version = "5.3.999";
$responsible = "studer + raimann ag - Team Custom 1";
$responsible_mail = "support-custom1@studer-raimann.ch";
