<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\FlashcardQuestions\Object\Obj;
use srag\DIC\DICTrait;

/**
 * Class ilObjFlashcardQuestionsAccess
 *
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilObjFlashcardQuestionsAccess extends ilObjectPluginAccess {

	use DICTrait;
	const PLUGIN_CLASS_NAME = ilFlashcardQuestionsPlugin::class;
	/**
	 * @var self
	 */
	protected static $instance = NULL;


	/**
	 * @return self
	 */
	public static function getInstance(): self {
		if (self::$instance === NULL) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * ilObjFlashcardQuestionsAccess constructor
	 */
	public function __construct() {
		parent::__construct();
	}


	/**
	 * @param string   $a_cmd
	 * @param string   $a_permission
	 * @param int|null $a_ref_id
	 * @param int|null $a_obj_id
	 * @param int|null $a_user_id
	 *
	 * @return bool
	 */
	public function _checkAccess(/*string*/
		$a_cmd, /*string*/
		$a_permission, /*?int*/
		$a_ref_id = NULL, /*?int*/
		$a_obj_id = NULL, /*?int*/
		$a_user_id = NULL): bool {
		if ($a_ref_id === NULL) {
			$a_ref_id = filter_input(INPUT_GET, "ref_id");
		}

		if ($a_obj_id === NULL) {
			$a_obj_id = ilObjFlashcardQuestions::_lookupObjectId($a_ref_id);
		}

		if ($a_user_id == NULL) {
			$a_user_id = self::dic()->user()->getId();
		}

		switch ($a_permission) {
			case "visible":
			case "read":
				return boolval((self::dic()->access()->checkAccessOfUser($a_user_id, $a_permission, "", $a_ref_id) && !self::_isOffline($a_obj_id))
					|| self::dic()->access()->checkAccessOfUser($a_user_id, "write", "", $a_ref_id));

			case "delete":
				return boolval(self::dic()->access()->checkAccessOfUser($a_user_id, "delete", "", $a_ref_id)
					|| self::dic()->access()->checkAccessOfUser($a_user_id, "write", "", $a_ref_id));

			case "write":
			case "edit_permission":
			default:
				return boolval(self::dic()->access()->checkAccessOfUser($a_user_id, $a_permission, "", $a_ref_id));
		}
	}


	/**
	 * @param string   $a_cmd
	 * @param string   $a_permission
	 * @param int|null $a_ref_id
	 * @param int|null $a_obj_id
	 * @param int|null $a_user_id
	 *
	 * @return bool
	 */
	protected static function checkAccess(string $a_cmd, string $a_permission, /*?int*/
		$a_ref_id = NULL, /*?int*/
		$a_obj_id = NULL, /*?int*/
		$a_user_id = NULL) {
		return self::getInstance()->_checkAccess($a_cmd, $a_permission, $a_ref_id, $a_obj_id, $a_user_id);
	}


	/**
	 * @param object|string $class
	 * @param string        $cmd
	 */
	public static function redirectNonAccess($class, string $cmd = "") {
		ilUtil::sendFailure(self::plugin()->translate("permission_denied", ilObjFlashcardQuestionsGUI::LANG_MODULE_OBJECT), true);

		if (is_object($class)) {
			self::dic()->ctrl()->clearParameters($class);
			self::dic()->ctrl()->redirect($class, $cmd);
		} else {
			self::dic()->ctrl()->clearParametersByClass($class);
			self::dic()->ctrl()->redirectByClass($class, $cmd);
		}
	}


	/**
	 * @param int $obj_id
	 *
	 * @return bool
	 */
	public static function _isOffline(/*?int*/
		$a_obj_id): bool {
		$object = Obj::getObjectById(intval($a_obj_id));

		if ($object !== NULL) {
			return (!$object->isOnline());
		} else {
			return true;
		}
	}


	/**
	 * @param int|null $ref_id
	 *
	 * @return bool
	 */
	public static function hasVisibleAccess(/*?int*/
		$ref_id = NULL): bool {
		return self::checkAccess("visible", "visible", $ref_id);
	}


	/**
	 * @param int|null $ref_id
	 *
	 * @return bool
	 */
	public static function hasReadAccess(/*?int*/
		$ref_id = NULL): bool {
		return self::checkAccess("read", "read", $ref_id);
	}


	/**
	 * @param int|null $ref_id
	 *
	 * @return bool
	 */
	public static function hasWriteAccess(/*?int*/
		$ref_id = NULL): bool {
		return self::checkAccess("write", "write", $ref_id);
	}


	/**
	 * @param int|null $ref_id
	 *
	 * @return bool
	 */
	public static function hasDeleteAccess(/*?int*/
		$ref_id = NULL): bool {
		return self::checkAccess("delete", "delete", $ref_id);
	}


	/**
	 * @param int|null $ref_id
	 *
	 * @return bool
	 */
	public static function hasEditPermissionAccess(/*?int*/
		$ref_id = NULL): bool {
		return self::checkAccess("edit_permission", "edit_permission", $ref_id);
	}
}
