<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\FlashcardQuestions\Object\Obj;
use srag\Plugins\FlashcardQuestions\Question\xfcqQuestion;
use srag\RemovePluginDataConfirm\FlashcardQuestions\RepositoryObjectPluginUninstallTrait;

/**
 * Class ilFlashcardQuestionsPlugin
 *
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilFlashcardQuestionsPlugin extends ilRepositoryObjectPlugin {

	use RepositoryObjectPluginUninstallTrait;
	const PLUGIN_ID = "xfcq";
	const PLUGIN_NAME = "FlashcardQuestions";
	const PLUGIN_CLASS_NAME = self::class;
	const REMOVE_PLUGIN_DATA_CONFIRM_CLASS_NAME = FlashcardQuestionsRemoveDataConfirm::class;
	/**
	 * @var self|null
	 */
	protected static $instance = NULL;


	/**
	 * @return self
	 */
	public static function getInstance() {
		if (self::$instance === NULL) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * ilFlashcardQuestionsPlugin constructor
	 */
	public function __construct() {
		parent::__construct();
	}


	/**
	 * @return string
	 */
	public function getPluginName() {
		return self::PLUGIN_NAME;
	}


	/**
	 * @inheritdoc
	 */
	protected function deleteData()/*: void*/ {
	    /** @var xfcqQuestion $xfcqQuestion */
        foreach (xfcqQuestion::get() as $xfcqQuestion) {
	        $page = new xfcqPageObject($xfcqQuestion->getPageIdQuestion());
	        $page->delete();
	        $page = new xfcqPageObject($xfcqQuestion->getPageIdAnswer());
	        $page->delete();
        }
		self::dic()->database()->dropTable(Obj::TABLE_NAME, false);
		self::dic()->database()->dropTable(xfcqQuestion::TABLE_NAME, false);
	}
}
