<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\FlashcardQuestions\Config;

use ilFlashcardQuestionsConfigGUI;
use ilFlashcardQuestionsPlugin;
use ilTextInputGUI;
use srag\ActiveRecordConfig\ActiveRecordConfigFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @package srag\Plugins\FlashcardQuestions\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ConfigFormGUI extends ActiveRecordConfigFormGUI {

	const PLUGIN_CLASS_NAME = ilFlashcardQuestionsPlugin::class;


	/**
	 * @inheritdoc
	 */
	protected function setForm()/*: void*/ {
		parent::setForm();

		$some = new ilTextInputGUI(self::plugin()->translate("some", ilFlashcardQuestionsConfigGUI::LANG_MODULE_CONFIG), "some");
		$some->setRequired(true);
		$some->setValue(Config::getSome());
		$this->addItem($some);
		// TODO: Implement ConfigFormGUI
	}


	/**
	 * @inheritdoc
	 */
	public function updateConfig()/*: void*/ {
		$some = $this->getInput("some");
		Config::setSome($some);
	}
}
