<#1>
<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */

\srag\Plugins\FlashcardQuestions\Object\Obj::updateDB();
\srag\Plugins\FlashcardQuestions\Question\xfcqQuestion::updateDB();
?>
<#2>
<?php
\srag\DIC\FlashcardQuestions\DICStatic::dic()->database()->modifyTableColumn('copg_pobj_def', 'component', array( 'length' => 120 ));
\srag\DIC\FlashcardQuestions\DICStatic::dic()->database()->insert('copg_pobj_def', array(
	'parent_type' => array( 'text', ilFlashcardQuestionsPlugin::PLUGIN_ID ),
	'class_name' => array( 'text', xfcqPageObject::class ),
	'directory' => array( 'text', 'classes/PageObject' ),
	'component' => array( 'text', substr(\srag\DIC\FlashcardQuestions\DICStatic::plugin(\ilFlashcardQuestionsPlugin::class)->directory(), 2) )
));
?>
<#3>
<?php
\srag\Plugins\FlashcardQuestions\Question\xfcqQuestion::updateDB();
?>
<#4>
<?php
\srag\Plugins\FlashcardQuestions\Config\Config::updateDB();
?>
<#5>
<?php
\srag\Plugins\FlashcardQuestions\Object\Obj::updateDB();
?>
