<#1>
<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.7.2
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */

\srag\Plugins\FlashcardQuestions\Config\Config::updateDB();
\srag\Plugins\FlashcardQuestions\Object\Obj::updateDB();
\srag\Plugins\FlashcardQuestions\Question\xfcqQuestion::updateDB();
?>
